services:
  app:
    image: gw-currency-wallet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    command: postgres
    env_file:
      - .env
    ports:
      - "5433:5432"  # Порт 5433 на хосте, 5432 в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallets"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: