services:
  app:
    image: gw-currency-wallet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - config.env
    depends_on:
      db_wallet:
        condition: service_healthy
    networks:
      - mynetwork

  db_wallet:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"  # Порт 5433 на хосте, 5432 в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/storages/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wallet_db"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    external: true